"""add japanese text fields to posts

Revision ID: 2b7086592746
Revises: e0fb97b20d2c
Create Date: 2026-02-16 17:33:20.100806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7086592746'
down_revision: Union[str, None] = 'e0fb97b20d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title_ja', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('content_ja', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('excerpt_ja', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'excerpt_ja')
    op.drop_column('posts', 'content_ja')
    op.drop_column('posts', 'title_ja')
    # ### end Alembic commands ###
